### ISSUE TITLE
KeepRight Errors not displayed

### ISSUE THREAD

**Issue by rjw62** [eMerzh/OpenFixMap#9]
A few months ago, it seems that the KeepRight error display has stopped working. You can tap the "fetch errors" text, and the app will sit thinking for a bit, but when it is done, no errors are displayed. Errors from other error reporting platforms still seem to show up ok.

I think the problem may be because KeepRight has changed the URL and query string format for its GPS export. According to http://keepright.ipax.at/interfacing.php the export URL is at http://keepright.ipax.at/export.php whereas at line 85 of OpenFixMap/src/net/bmaron/openfixmap/ErrorParsers/KeepRightCSVParser.java the URL http://keepright.ipax.at/points.php is used. As well as correcting the URL, I think the query string may need updating too. In particular export.php seems to use a bounding box rather than a centre (lat,lon) pair now.

**Comment by caigner** [comment]
I just installed OpenFixMap, but when I fetch errors from KeepRight, no errors are downloaded.

**Comment by brycenesbitt** [comment]
Keepright has a new maintainer, Jan Michel, and a new github:https://github.com/keepright/keepright

**Comment by eMerzh** [comment]
Thanks a lot you guys for raising the problem...

Long time no see on OFM, but i want to put a litte order in those things :)

Here is the fix, i'll try to do some other things then i'll publish a new version :)
